name: laervi
channels:
  - defaults
dependencies:
  - bokeh=0.12.14=py36_0
  - bzip2=1.0.6=h9a117a8_4
  - ca-certificates=2017.08.26=h1d4fec5_0
  - cairo=1.14.12=h77bcde2_0
  - certifi=2018.1.18=py36_0
  - click=6.7=py36h5253387_0
  - cloudpickle=0.5.2=py36_1
  - cycler=0.10.0=py36h93f1223_0
  - dask=0.17.0=py36_0
  - dask-core=0.17.0=py36_0
  - dbus=1.12.2=hc3f9b76_1
  - decorator=4.2.1=py36_0
  - distributed=1.21.0=py36_0
  - expat=2.2.5=he0dffb1_0
  - ffmpeg=3.4=h7264315_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - graphite2=1.3.10=hf63cedd_1
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - harfbuzz=1.7.4=hc5b324e_0
  - hdf5=1.10.1=h9caa474_1
  - heapdict=1.0.0=py36_2
  - icu=58.2=h9c2bf20_1
  - imageio=2.2.0=py36he555465_0
  - intel-openmp=2018.0.0=hc7b2577_8
  - jasper=1.900.1=hd497a04_4
  - jinja2=2.10=py36ha16c418_0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libopus=1.2.1=hb9ed12e_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.4.1=h5b8497f_0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.9=h28f6b97_0
  - libvpx=1.6.1=h888fd40_0
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.7=h26e45fe_0
  - locket=0.2.0=py36h787c0ad_1
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.1.2=py36h0e671d2_0
  - mkl=2018.0.1=h19d6760_4
  - msgpack-python=0.5.1=py36h6bb024c_0
  - ncurses=6.0=h9df7e31_2
  - networkx=2.1=py36_0
  - numpy=1.14.1=py36h3dfced4_1
  - olefile=0.45.1=py36_0
  - opencv=3.3.1=py36h6cbbc71_1
  - openssl=1.0.2n=hb7f436b_0
  - packaging=16.8=py36ha668100_1
  - pandas=0.22.0=py36hf484d3e_0
  - partd=0.3.8=py36h36fd896_0
  - pcre=8.41=hc27e229_1
  - pillow=5.0.0=py36h3deb7b8_0
  - pip=9.0.1=py36h6c6f9ce_4
  - pixman=0.34.0=hceecf20_3
  - psutil=5.4.3=py36h14c3975_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - python=3.6.4=hc3d631a_1
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2018.3=py36_0
  - pywavelets=0.5.2=py36he602eb0_0
  - pyyaml=3.12=py36hafb9ca4_1
  - qt=5.6.2=hd25b39d_14
  - readline=7.0=ha6073c6_4
  - scikit-image=0.13.1=py36h14c3975_1
  - scipy=1.0.0=py36hbf646e7_0
  - setuptools=38.5.1=py36_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sortedcontainers=1.5.9=py36_0
  - sqlite=3.22.0=h1bed415_0
  - tblib=1.3.2=py36h34cf8b6_0
  - tk=8.6.7=hc745277_3
  - toolz=0.9.0=py36_0
  - tornado=4.5.3=py36_0
  - wheel=0.30.0=py36hfd4bba0_1
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zict=0.1.3=py36h3a3bf81_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - dlib==19.9.0

